CREATE DATABASE AdvancedMappingsManyToMany DEFAULT CHARACTER SET 'utf8'
  DEFAULT COLLATE 'utf8_unicode_ci';

USE AdvancedMappingsManyToMany;

CREATE TABLE schools (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL
) ENGINE = InnoDB;

CREATE TABLE students (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL
) ENGINE = InnoDB;

CREATE TABLE schools_students (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  school_id BIGINT UNSIGNED NOT NULL,
  student_id BIGINT UNSIGNED NOT NULL,
  CONSTRAINT fk_school_id FOREIGN KEY (school_id)
    REFERENCES schools (id) ON DELETE CASCADE,
  CONSTRAINT fk_student_id FOREIGN KEY (student_id)
    REFERENCES students (id) ON DELETE CASCADE
) ENGINE = InnoDB;

